[package]
name = "svdselector"
version = "0.2.0"
authors = ["Andrey Zgarbul <zgarbul.andrey@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "0.14.3"
svd-parser = "0.11"
indexmap = "1.7"
lazy-regex = "2.2.2"
anyhow = "1.0.45"
